version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
      - 9090:9090     # prometheus access port
    container_name: prometheus
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    container_name: grafana
    ports:
      - 3000:3000     # grafana access port